tile_sets:
  cave:
    size: 36
    height: 13

dungeons:
  dungeon1:
    min_floors: 2
    max_floors: 5
    floors:
      1:
        tile_sets:
        - cave
        min_rooms: 4
        max_rooms: 12
        chest_chance: 0.8
        min_items: 1
        max_items: 3
        items:
        - item1
        - item2
        - item2
        - item3
        - item4
        - item4
        - item4
        - item5
        - item6
        - item7
        - item7
        - item7
        - item8
        - item8
        - item9
        - item9
        - item9
        - item9
        - item10
      2:
        tile_sets:
        - cave
        min_rooms: 9
        max_rooms: 15
        chest_chance: 0.1
        min_items: 4
        max_items: 9
        items:
        - item2
        - item2
        - item3
        - item4
        - item4
        - item4
        - item5
        - item7
        - item7
        - item8
        - item8
        - item9
        - item9
      3:
        tile_sets:
        - cave
        min_rooms: 7
        max_rooms: 15
        chest_chance: 0.5
        min_items: 1
        max_items: 6
        items:
        - item1
        - item2
        - item3
        - item4
        - item4
        - item5
        - item6
        - item7
        - item7
        - item7
        - item8
        - item8
        - item9
        - item9
        - item10
      4:
        tile_sets:
        - cave
        min_rooms: 10
        max_rooms: 20
        chest_chance: 0.2
        min_items: 2
        max_items: 3
        items:
        - item1
        - item1
        - item1
        - item1
        - item4
        - item4
        - item4
        - item7
        - item7
        - item8
        - item8
        - item9
        - item9
        - item9
        - item9
        - item10
      5:
        tile_sets:
        - cave
        min_rooms: 6
        max_rooms: 10
        chest_chance: 0.3
        min_items: 3
        max_items: 5
        items:
        - item1
        - item1
        - item2
        - item3
        - item3
        - item4
        - item4
        - item5
        - item6
        - item6
        - item6
        - item7
        - item8
        - item8
        - item8
        - item9
        - item9
        - item10
        - item10