name: ProceduralDungeons
author: Scholtes
version: 1.0.6-STABLE
description: ProceduralDungeons
main: me.scholtes.proceduraldungeons.ProceduralDungeons
api-version: 1.16
depend: [WorldEdit, MythicMobs]

commands:
  dungeon:
    description: Main dungeon command
  party:
    description: Main party command